[package]
name = "zune-imageprocs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[features]
avx2 = []
sse2 = []
sse3 = []
sse41 = []

default=["avx2","sse2","sse3","sse41"]