name: Fuzz

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fuzz deflate
        run:
          name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Fuzz deflate
        run: cargo +nightly fuzz run --fuzz-dir zune-inflate/fuzz roundtrip -- --runs=2000
      - name: Fuzz zlib
        run: cargo +nightly fuzz run --fuzz-dir zune-inflate/fuzz roundtrip_zlib -- --runs=2000


