[package]
name = "zune-jpeg"
version = "0.2.0"
authors = ["caleb <etemesicaleb@gmail.com>"]
edition = "2021"
repository = "https://github.com/etemesi254/zune-jpeg"
license = "MIT OR Apache-2.0"
keywords = ["jpeg", "jpeg-decoder", "decoder"]
categories = ["multimedia::images"]
exclude = ["/benches/images/", "/tests/*", "/.idea/*", "/.gradle/*"]
description = "The fastest jpeg decoder in the west"

[lib]
crate-type = ["cdylib", "rlib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
x86 = []
default = ["x86"]

[dependencies]
log = "0.4.11" # logging facilities
zune-core = { path = "../zune-core" }

[dev-dependencies]
zune-tests = { path = "../zune-tests" }
mozjpeg = "0.9.2"
jpeg-decoder = "0.2.6"

[dev-dependencies.criterion]
version = "0.4.0"
default-features = false
features = ["html_reports"]

[[bench]]
name = "decode"
harness = false

[[bench]]
name = "decode_grayscale"
harness = false


[[bench]]
name = "decode_prog"
harness = false

[[bench]]
name = "decode_x86"
harness = false


