name: Rust

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for different architectures
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc

          - name: MacOS
            os: macos-latest
            target: x86_64-apple-darwin

          - name: Web
            os: ubuntu-latest
            target: wasm32-unknown-unknown

    runs-on: ${{ matrix.os }}


    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - run: cargo build --verbose