name: Fuzz PSD

on:
  push:
    branches: [ "main","dev" ]
    paths:
      - 'crates/zune-psd/**'
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ "main" ,"dev" ]
    paths:
      - 'crates/zune-psd/**'


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly

      - name: Install
        run: cargo install cargo-fuzz

      - name: Normal Fuzz testing.
        run: cargo +nightly fuzz run --fuzz-dir crates/zune-psd/fuzz decode_buffer test-images/psd -j2 -- -timeout=10s -max_total_time=60
