name: Build zune-image with single features.

env:
  CARGO_TERM_COLOR: always
on:
  push:
    branches: [ "main","dev" ]
    paths:
      - 'crates/zune-image/**'
  pull_request:
    branches: [ "main" ,"dev" ]
    paths:
      - 'crates/zune-image/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    strategy:
      matrix:
        features: [ "image_formats", "serde-support", "metadata", "threads", "simd", "log","jpeg", "ppm", "png", "psd", "farbfeld", "qoi", "jpeg-xl", "hdr", "bmp" ]
        imageproc: [ "avx2","sse2","sse3","sse41","log","exif","threads" ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check independent feature build Basics
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p zune-image --no-default-features -F ${{ matrix.features }}
      - name: Check independent features in zune-imageprocs
        uses: actions-rs/cargo@v1
        with:
          command: build
            -p zune-imageprocs --no-default-features -F ${{ matrix.imageproc }}

