name: Rust

on:
  push:
    branches: [ "main","dev","gif" ]
  pull_request:
    branches: [ "main","dev" ,"gif" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.os }}


    steps:
      - uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: RUSTFLAGS="-C debuginfo=2"  cargo test --verbose --release --workspace --no-fail-fast
