name: Semver checks

on:
  push:
    branches: [ "main","dev" ]
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ "main" ,"dev" ]


jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          manifest-path: zune-image/Cargo.toml